# Generated by Django 5.0.2 on 2025-01-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_categorygroup_classificationresult_category_group_and_more'),
        ('fileapp', '0002_alter_textinput_classification_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinput',
            name='llm_model',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='textinput',
            name='llm_provider',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='classification_results',
            field=models.ManyToManyField(blank=True, to='classifier.classificationresult'),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
