# Generated by Django 5.0.2 on 2025-01-20 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('server_type', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], max_length=10)),
                ('server_host', models.CharField(max_length=255)),
                ('server_port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=1000)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.JSONField()),
                ('content', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('received_date', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=CASCADE, to='emailapp.emailaccount')),
                ('classification_result', models.ForeignKey(blank=True, null=True, on_delete=CASCADE, to='classifier.classificationresult')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification_result', models.ForeignKey(blank=True, null=True, on_delete=CASCADE, to='classifier.classificationresult')),
                ('email', models.ForeignKey(on_delete=CASCADE, to='emailapp.emailmessage')),
            ],
        ),
        migrations.CreateModel(
            name='EmailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[
                    ('txt', 'Text File'),
                    ('html', 'HTML File'),
                    ('eml', 'EML File'),
                    ('oft', 'OFT File'),
                    ('msg', 'MSG File'),
                    ('other', 'Other'),
                ], max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('email_content', models.JSONField(blank=True, null=True)),
                ('classification_result', models.JSONField(blank=True, null=True)),
                ('classification_level', models.CharField(
                    choices=[
                        ('rule', 'Rule Engine'),
                        ('fasttext', 'FastText Model'),
                        ('bert', 'BERT Model'),
                        ('llm', 'LLM Model'),
                        ('unknown', 'Unknown'),
                    ],
                    default='unknown',
                    max_length=20
                )),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sender_domains', models.JSONField(default=list)),
                ('subject_keywords', models.JSONField(default=list)),
                ('body_keywords', models.JSONField(default=list)),
                ('min_attachments', models.IntegerField(default=0)),
                ('max_attachments', models.IntegerField(blank=True, null=True)),
                ('min_attachment_size', models.BigIntegerField(default=0)),
                ('max_attachment_size', models.BigIntegerField(blank=True, null=True)),
                ('classification', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
