# Generated by Django 5.0.2 on 2025-01-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_categorygroup_classificationresult_category_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationresult',
            name='rule',
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='llm_model',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='llm_provider',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
