# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - contents-classify

on:
  push:
    branches:
      - az_deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
        
      # - name: Collect static files
      #   run: |
      #     python backend/manage.py collectstatic --noinput
          
      # Optional: Add step to run tests here

      - name: Create deployment package
        run: |
          # 创建部署包目录
          mkdir deploy_package
          # 复制必要文件
          cp -r backend deploy_package/
          cp -r frontend/build deploy_package/frontend_static
          cp requirements.txt deploy_package/
          # 创建启动脚本
          echo "gunicorn --chdir backend backend.wsgi:application --log-file -" > deploy_package/startup.sh
          chmod +x deploy_package/startup.sh
          # 打包
          cd deploy_package
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'contents-classify'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_566A37D6118F4CC58C0D7A3FF4D50153 }}